language: php

cache:
    directories:
        - $HOME/.composer/cache

env:
    - PHP_CS_FIXER_IGNORE_ENV=true

php:
    - 7.4snapshot

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

before_script:
    - wget https://github.com/infection/infection/releases/download/0.14.1/infection.phar
    - wget https://github.com/infection/infection/releases/download/0.14.1/infection.phar.asc
    - gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 493B4AA0
    - gpg --with-fingerprint --verify infection.phar.asc infection.phar
    - chmod +x infection.phar

before_install:
    - pecl install xdebug
    - echo "zend_extension=xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - travis_retry composer self-update --no-interaction

install:
    - travis_retry composer update --no-interaction --prefer-dist

script:
    - composer check-style
    - composer test-ci
    - ./infection.phar --min-msi=48 --min-covered-msi=70 --threads=4

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
